apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
  - targetPort: {{ .Values.port }}
    port: 80
    protocol: TCP
    name: http
